### ISSUE TITLE
Optimize images

### ISSUE THREAD

**Issue by kornelski** [bencallahan/compressive-test#1]
https://github.com/bencallahan/compressive-test/blob/master/images/test/0003.jpg can be losslessly reduced by 41% using ImageOptim.

**Comment by bencallahan** [comment]
@pornel Great point—these could certainly be better optimized. Given the nature of this specific test, I wondered if it might be better to use what many people are using, just a simple PhotoShop export, so that the tests are as “real world” as possible. Make sense? Anyone think we should better optimize these?

**Comment by kornelski** [comment]
Depends whether you want to somehow objectively measure what can be achieved with JPEG compression or measure how Photoshop exports different images.

Photoshop's Save For Web is generally poor, and has quirks like enabling chroma subsampling depending on quality setting (I wonder whether that makes "compressive" images actually compress: not because JPEGs ability in low qualities, but because Photoshop compresses JPEGs less badly in qualities below 50…)

**Comment by bencallahan** [comment]
Yeah, it certainly seems like the savings with these files is minimal. I’ll play around with some better compression tools and see what we get! Thanks for the thoughts.
